on:
    schedule:
        - cron: "0 0 1 * *" # 00:00 UTC every day
jobs:
    keep-scheduled-workflow-activity:
        uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v1
