jobs:
  keep-scheduled-workflow-activity:
    uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@main
  overload-call:
    runs-on: ubuntu-latest
    steps:
      - uses: leafo/gh-actions-lua@master
      - uses: leafo/gh-actions-luarocks@master
      - id: cache
        uses: actions/cache@main
        with:
          key: luarocks-cjson
          path: |
            ~/.luarocks/lib/lua/5.4
            ~/.luarocks/share/lua/5.4
            .luarocks/lib/lua/5.4
            .luarocks/share/lua/5.4
      - if: steps.cache.outputs.cache-hit != 'true'
        run: luarocks install lua-cjson
      - uses: actions/checkout@main
      - uses: actions/checkout@main
        with:
          repository: redis/docs
          sparse-checkout: |
            data/resp2_replies.json
            data/resp3_replies.json
      - run: ls
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: