on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:
jobs:
    keep-scheduled-workflow-activity:
        uses: WaterLemons2k/scheduled-workflow-activity-action/.github/workflows/reusable.yml@v1
    overload-call:
        # outputs:
        #     output1: ${{ steps.step1.outputs }}
        runs-on: ubuntu-latest
        steps:
          - run: docker images
          - uses: ScribeMD/docker-cache@0.5.0
            with:
                key: docker-${{ runner.os }}
          - run: docker images
          - uses: mileschou/lua-action@master
            with:
                args: lua -v
          - run: docker images